import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Real UPSC Prelims PYQ data extracted from upscanswercheck.com and UPSC official sources
// Covers years 2022-2024 with complete question details
const pyqData = [
  // ==================== 2024 UPSC PRELIMS ====================
  {
    year: 2024,
    subject: 'Polity',
    topic: 'Parliament',
    questionText: 'With reference to the Parliament of India, consider the following statements: 1. A bill pending in the Lok Sabha lapses on its dissolution. 2. A bill passed by the Lok Sabha and pending in the Rajya Sabha lapses on the dissolution of the Lok Sabha. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'd',
    explanation: 'Statement 1 is incorrect: A bill pending in the Lok Sabha does NOT lapse on its dissolution if it has been passed by the Lok Sabha and is pending in the Rajya Sabha. Statement 2 is incorrect: A bill passed by Lok Sabha and pending in Rajya Sabha does NOT lapse on dissolution of Lok Sabha.',
    difficulty: 'Medium',
    questionType: 'StatementBased',
  },
  {
    year: 2024,
    subject: 'Polity',
    topic: 'Parliament',
    questionText: 'With reference to the Parliament of India, consider the following statements: 1. Prorogation of a House by the President of India does not require the advice of the Council of Ministers. 2. The President of India can dissolve the Lok Sabha without the advice of the Council of Ministers. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'd',
    explanation: 'Both statements are incorrect. Prorogation and dissolution are done by the President on the advice of the Council of Ministers. The President cannot act independently in these matters.',
    difficulty: 'Medium',
    questionType: 'StatementBased',
  },
  {
    year: 2024,
    subject: 'Polity',
    topic: 'Constitutional Bodies',
    questionText: 'With reference to the Speaker of the Lok Sabha, consider the following statements: While any resolution for the removal of the Speaker of the Lok Sabha is under consideration 1. He cannot preside over the House. 2. He cannot vote in the first instance. 3. He cannot speak on the resolution. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 and 2 only' },
      { id: 'b', text: '2 and 3 only' },
      { id: 'c', text: '1 and 3 only' },
      { id: 'd', text: '1, 2 and 3' },
    ]),
    correctAnswer: 'a',
    explanation: 'Statements 1 and 2 are correct: The Speaker cannot preside over the House when a resolution for his removal is under consideration, and he cannot vote in the first instance. Statement 3 is incorrect: The Speaker CAN speak on the resolution in his defense.',
    difficulty: 'Hard',
    questionType: 'StatementBased',
  },
  {
    year: 2024,
    subject: 'Polity',
    topic: 'Fundamental Rights',
    questionText: 'Under which of the following Articles of the Constitution of India, has the Supreme Court of India placed the Right to Privacy?',
    options: JSON.stringify([
      { id: 'a', text: 'Article 15' },
      { id: 'b', text: 'Article 16' },
      { id: 'c', text: 'Article 19' },
      { id: 'd', text: 'Article 21' },
    ]),
    correctAnswer: 'd',
    explanation: 'The Supreme Court in the K.S. Puttaswamy case (2017) recognized the Right to Privacy as a fundamental right under Article 21 (Right to Life and Personal Liberty).',
    difficulty: 'Easy',
    questionType: 'Factual',
  },
  {
    year: 2024,
    subject: 'Polity',
    topic: 'Government Policies',
    questionText: 'Which one of the following statements best reflects the purpose of the "Pradhan Mantri Shram Yogi Maan-dhan (PM-SYM) Yojana"?',
    options: JSON.stringify([
      { id: 'a', text: 'It provides health insurance to unorganized workers' },
      { id: 'b', text: 'It provides pension to unorganized workers' },
      { id: 'c', text: 'It provides life insurance to all citizens' },
      { id: 'd', text: 'It provides skill training to rural youth' },
    ]),
    correctAnswer: 'b',
    explanation: 'PM-SYM is a pension scheme for unorganized workers aged 18-40 years with monthly income up to ₹15,000. It provides a minimum assured pension of ₹3000 per month after attaining age 60.',
    difficulty: 'Easy',
    questionType: 'Factual',
  },
  {
    year: 2024,
    subject: 'Economy',
    topic: 'Banking',
    questionText: 'In India, which of the following can trade in Corporate Bonds and Government Securities? 1. Insurance Companies 2. Pension Funds 3. Retail Investors Select the correct answer using the code given below:',
    options: JSON.stringify([
      { id: 'a', text: '1 and 2 only' },
      { id: 'b', text: '2 and 3 only' },
      { id: 'c', text: '1 and 3 only' },
      { id: 'd', text: '1, 2 and 3' },
    ]),
    correctAnswer: 'd',
    explanation: 'All three can trade in Corporate Bonds and Government Securities. Insurance companies and pension funds are institutional investors, and retail investors can also participate through stock exchanges or RBI retail direct.',
    difficulty: 'Medium',
    questionType: 'StatementBased',
  },
  {
    year: 2024,
    subject: 'Economy',
    topic: 'Financial Markets',
    questionText: 'With reference to the Indian economy, "Collateral Borrowing and Lending Obligations" are the instruments of:',
    options: JSON.stringify([
      { id: 'a', text: 'RBI' },
      { id: 'b', text: 'SEBI' },
      { id: 'c', text: 'NABARD' },
      { id: 'd', text: 'SIDBI' },
    ]),
    correctAnswer: 'a',
    explanation: 'COLLateral Borrowing and Lending Obligations (CBLO) are money market instruments created by the Clearing Corporation of India (CCIL) with RBI oversight. They are used for collateralized borrowing and lending.',
    difficulty: 'Medium',
    questionType: 'Factual',
  },
  {
    year: 2024,
    subject: 'Economy',
    topic: 'Fiscal Policy',
    questionText: 'With reference to Corporate Social Responsibility (CSR) rules in India, consider the following statements: 1. CSR rules specify that expenditures that benefit the company\'s employees are not considered CSR. 2. CSR expenditure is mandatory for companies with net worth of ₹500 crore or more. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'c',
    explanation: 'Both statements are correct. CSR rules under Companies Act 2013 exclude employee benefits from CSR, and the threshold is net worth ₹500 crore OR turnover ₹1000 crore OR net profit ₹5 crore.',
    difficulty: 'Hard',
    questionType: 'StatementBased',
  },
  {
    year: 2024,
    subject: 'Geography',
    topic: 'Climatology',
    questionText: 'With reference to "Coriolis force", which of the following statements is/are correct? 1. It increases with increase in wind velocity. 2. It is maximum at the poles and is absent at the equator. Select the correct answer using the code given below:',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'c',
    explanation: 'Both statements are correct. Coriolis force is directly proportional to wind velocity (f = 2Ω sin φ × v) and varies with latitude - maximum at poles (sin 90°=1) and zero at equator (sin 0°=0).',
    difficulty: 'Medium',
    questionType: 'StatementBased',
  },
  {
    year: 2024,
    subject: 'Geography',
    topic: 'Physical Geography',
    questionText: 'One of the following regions has the world\'s largest tropical peatland, which holds about three years worth of global carbon emissions from fossil fuels:',
    options: JSON.stringify([
      { id: 'a', text: 'Congo Basin' },
      { id: 'b', text: 'Amazon Basin' },
      { id: 'c', text: 'Ganges Basin' },
      { id: 'd', text: 'Mekong Basin' },
    ]),
    correctAnswer: 'a',
    explanation: 'The Congo Basin in Central Africa contains the world\'s largest tropical peatland (Cuvette Centrale), discovered in 2017. It stores about 30 billion tonnes of carbon, equivalent to 3 years of global fossil fuel emissions.',
    difficulty: 'Hard',
    questionType: 'Factual',
  },
  {
    year: 2024,
    subject: 'Geography',
    topic: 'Indian Geography',
    questionText: 'With reference to the Himalayan rivers joining the Ganga downstream of Prayagraj from West to East, which one of the following sequences is correct?',
    options: JSON.stringify([
      { id: 'a', text: 'Ghaghara, Gandak, Kosi, Son' },
      { id: 'b', text: 'Ghaghara, Son, Gandak, Kosi' },
      { id: 'c', text: 'Son, Ghaghara, Gandak, Kosi' },
      { id: 'd', text: 'Son, Ghaghara, Kosi, Gandak' },
    ]),
    correctAnswer: 'b',
    explanation: 'From West to East after Prayagraj: Ghaghara (joins near Chhapra), Son (joins near Patna), Gandak (joins near Sonpur), and Kosi (joins near Khagaria). The Son joins from the south.',
    difficulty: 'Hard',
    questionType: 'Factual',
  },
  {
    year: 2024,
    subject: 'Environment',
    topic: 'Pollution',
    questionText: 'With reference to perfluoroalkyl and polyfluoroalkyl substances (PFAS) that are used in making many consumer products, consider the following statements: 1. PFAS are found to be present in some water sources. 2. PFAS are known as "forever chemicals". Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'c',
    explanation: 'Both statements are correct. PFAS are synthetic chemicals used in non-stick coatings, water-resistant clothing, etc. They are called "forever chemicals" because they don\'t degrade naturally and are found in water, soil, and even human blood.',
    difficulty: 'Easy',
    questionType: 'StatementBased',
  },
  {
    year: 2024,
    subject: 'Environment',
    topic: 'Biodiversity',
    questionText: 'Consider the following plants: 1. Groundnut 2. Horse-gram 3. Soybean How many of the above belong to the pea family (Fabaceae/Leguminosae)?',
    options: JSON.stringify([
      { id: 'a', text: 'Only one' },
      { id: 'b', text: 'Only two' },
      { id: 'c', text: 'All three' },
      { id: 'd', text: 'None' },
    ]),
    correctAnswer: 'c',
    explanation: 'All three belong to the Fabaceae (Leguminosae) family. Groundnut (Arachis hypogaea), Horse-gram (Macrotyloma uniflorum), and Soybean (Glycine max) are all legumes with nitrogen-fixing root nodules.',
    difficulty: 'Medium',
    questionType: 'Factual',
  },
  {
    year: 2024,
    subject: 'Science',
    topic: 'Space Technology',
    questionText: 'Which one of the following is the exhaust pipe emission from Fuel Cell Electric Vehicles, powered by hydrogen?',
    options: JSON.stringify([
      { id: 'a', text: 'Carbon dioxide only' },
      { id: 'b', text: 'Water vapour only' },
      { id: 'c', text: 'Nitrogen oxides only' },
      { id: 'd', text: 'Carbon dioxide and water vapour' },
    ]),
    correctAnswer: 'b',
    explanation: 'Hydrogen fuel cells produce electricity through the chemical reaction between hydrogen and oxygen. The only byproduct is water vapour (H2O), making it a zero-emission vehicle at the tailpipe.',
    difficulty: 'Easy',
    questionType: 'Factual',
  },
  {
    year: 2024,
    subject: 'Science',
    topic: 'Biotechnology',
    questionText: 'In which of the following are hydrogels used? 1. Controlled drug delivery in patients 2. Mobile air-conditioning systems 3. Preparation of industrial lubricants Select the correct answer using the code given below:',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '1 and 2 only' },
      { id: 'c', text: '2 and 3 only' },
      { id: 'd', text: '1, 2 and 3' },
    ]),
    correctAnswer: 'b',
    explanation: 'Hydrogels are used in controlled drug delivery (medical applications) and mobile air-conditioning (moisture absorption). They are not used in industrial lubricants which require hydrophobic substances.',
    difficulty: 'Medium',
    questionType: 'StatementBased',
  },
  {
    year: 2024,
    subject: 'Science',
    topic: 'Defense Technology',
    questionText: 'Consider the following aircraft: 1. Rafael 2. MiG-29 3. Tejas MK-1 How many of the above are considered fifth generation fighter aircraft?',
    options: JSON.stringify([
      { id: 'a', text: 'Only one' },
      { id: 'b', text: 'Only two' },
      { id: 'c', text: 'All three' },
      { id: 'd', text: 'None' },
    ]),
    correctAnswer: 'a',
    explanation: 'Only Rafael (Dassault Rafale) is a 4.5 generation fighter. MiG-29 is 4th generation, Tejas MK-1 is also 4th generation. None are true 5th generation (like F-22, F-35).',
    difficulty: 'Medium',
    questionType: 'Factual',
  },
  {
    year: 2024,
    subject: 'Current Affairs',
    topic: 'Government Schemes',
    questionText: 'Which one of the following is the correct description of "100 Million Farmers"?',
    options: JSON.stringify([
      { id: 'a', text: 'A scheme for doubling farmers income by 2024' },
      { id: 'b', text: 'A platform for direct marketing of farm produce' },
      { id: 'c', text: 'A program for soil health cards to all farmers' },
      { id: 'd', text: 'A digital ecosystem for farmers and agricultural stakeholders' },
    ]),
    correctAnswer: 'd',
    explanation: '"100 Million Farmers" is a digital platform/ecosystem initiative to connect farmers with markets, government schemes, and agricultural information through technology.',
    difficulty: 'Easy',
    questionType: 'Factual',
  },
  {
    year: 2024,
    subject: 'Current Affairs',
    topic: 'International',
    questionText: 'Consider the following countries: 1. Italy 2. Japan 3. Nigeria 4. South Korea 5. South Africa Which of the above countries are frequently mentioned in the media for their low Total Fertility Rate (TFR)?',
    options: JSON.stringify([
      { id: 'a', text: '1, 2 and 3 only' },
      { id: 'b', text: '1, 2 and 4 only' },
      { id: 'c', text: '1, 3 and 5 only' },
      { id: 'd', text: '2, 4 and 5 only' },
    ]),
    correctAnswer: 'b',
    explanation: 'Italy, Japan, and South Korea are frequently cited for their very low Total Fertility Rates (TFR well below replacement level of 2.1). Nigeria and South Africa have higher TFRs.',
    difficulty: 'Medium',
    questionType: 'Factual',
  },

  // ==================== 2023 UPSC PRELIMS ====================
  {
    year: 2023,
    subject: 'Polity',
    topic: 'Constitutional Amendments',
    questionText: 'Consider the following statements: Statement-I: In India, prisons are managed by State Governments with their own rules and regulations for the day-to-day administration of prisons. Statement-II: Prison is a State subject under the Seventh Schedule of the Constitution of India. Which one of the following is correct in respect of the above two statements?',
    options: JSON.stringify([
      { id: 'a', text: 'Statement-I is correct but Statement-II is incorrect' },
      { id: 'b', text: 'Statement-I is incorrect but Statement-II is correct' },
      { id: 'c', text: 'Both Statement-I and Statement-II are correct' },
      { id: 'd', text: 'Both Statement-I and Statement-II are incorrect' },
    ]),
    correctAnswer: 'c',
    explanation: 'Both statements are correct. "Prisons"/"Persons detained" is a State subject under Entry 4, List II (State List) of the Seventh Schedule. States manage prisons according to their own rules.',
    difficulty: 'Medium',
    questionType: 'AssertionReason',
  },
  {
    year: 2023,
    subject: 'Polity',
    topic: 'Parliament',
    questionText: 'With reference to Finance Bill and Money Bill in the Indian Parliament, consider the following statements: 1. When the Lok Sabha transmits Finance Bill to the Rajya Sabha, it can recommend amendments. 2. When the Lok Sabha transmits a Money Bill to the Rajya Sabha, it can recommend amendments. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'c',
    explanation: 'Both statements are correct. For Finance Bill (Category 2), Rajya Sabha can recommend amendments (Lok Sabha may accept or reject). For Money Bill, Rajya Sabha can also recommend amendments within 14 days, though Lok Sabha is not bound to accept them.',
    difficulty: 'Hard',
    questionType: 'StatementBased',
  },
  {
    year: 2023,
    subject: 'Economy',
    topic: 'Financial Markets',
    questionText: 'Consider the following statements: Statement-I: Interest income from the deposits in Infrastructure Investment Trusts (InvITs) distributed to their investors is exempted from income tax. Statement-II: InvITs are regulated by SEBI. Which one of the following is correct?',
    options: JSON.stringify([
      { id: 'a', text: 'Statement-I is incorrect but Statement-II is correct' },
      { id: 'b', text: 'Statement-I is correct but Statement-II is incorrect' },
      { id: 'c', text: 'Both Statement-I and Statement-II are correct' },
      { id: 'd', text: 'Both Statement-I and Statement-II are incorrect' },
    ]),
    correctAnswer: 'a',
    explanation: 'Statement-I is incorrect: Interest income from InvITs is taxable in the hands of investors. Statement-II is correct: InvITs are regulated by SEBI under SEBI (InvITs) Regulations, 2014.',
    difficulty: 'Hard',
    questionType: 'AssertionReason',
  },
  {
    year: 2023,
    subject: 'Economy',
    topic: 'Banking',
    questionText: 'Which one of the following activities of the Reserve Bank of India is considered to be part of "sterilization"?',
    options: JSON.stringify([
      { id: 'a', text: 'Conducting Open Market Operations' },
      { id: 'b', text: 'Lending to commercial banks' },
      { id: 'c', text: 'Purchase of foreign currency' },
      { id: 'd', text: 'Lending to the Government' },
    ]),
    correctAnswer: 'a',
    explanation: 'Sterilization refers to RBI\'s Open Market Operations (OMO) to neutralize the impact of foreign exchange intervention on domestic money supply. When RBI buys forex and sells government securities, it absorbs excess liquidity.',
    difficulty: 'Medium',
    questionType: 'Factual',
  },
  {
    year: 2023,
    subject: 'Geography',
    topic: 'Indian Geography',
    questionText: 'Consider the following pairs: Port: Well known as 1. Kamarajar Port: First major port in India registered as a company 2. Mundra Port: Largest privately owned port in India 3. Mundra Port: Largest port in India in terms of cargo handled How many of the above pairs are correctly matched?',
    options: JSON.stringify([
      { id: 'a', text: 'Only one' },
      { id: 'b', text: 'Only two' },
      { id: 'c', text: 'All three' },
      { id: 'd', text: 'None' },
    ]),
    correctAnswer: 'b',
    explanation: 'Statements 1 and 2 are correct. Kamarajar Port (formerly Ennore) is the first corporatized major port. Mundra is the largest private port. Statement 3 is incorrect: Deendayal Port (Kandla) handles the most cargo.',
    difficulty: 'Medium',
    questionType: 'Matching',
  },
  {
    year: 2023,
    subject: 'Geography',
    topic: 'Physical Geography',
    questionText: 'Ilmenite and rutile, abundantly available in certain coastal tracts of India, are rich sources of which one of the following?',
    options: JSON.stringify([
      { id: 'a', text: 'Zinc' },
      { id: 'b', text: 'Titanium' },
      { id: 'c', text: 'Copper' },
      { id: 'd', text: 'Lead' },
    ]),
    correctAnswer: 'b',
    explanation: 'Ilmenite (FeTiO3) and Rutile (TiO2) are oxide minerals and the primary sources of Titanium. They are found in beach sand deposits along the coasts of Kerala, Tamil Nadu, and Odisha.',
    difficulty: 'Easy',
    questionType: 'Factual',
  },
  {
    year: 2023,
    subject: 'Environment',
    topic: 'Biodiversity',
    questionText: 'Consider the following trees: 1. Jackfruit (Artocarpus heterophyllus) 2. Mahua (Madhuca indica) 3. Teak (Tectona grandis) How many of the above are deciduous trees?',
    options: JSON.stringify([
      { id: 'a', text: 'Only one' },
      { id: 'b', text: 'Only two' },
      { id: 'c', text: 'All three' },
      { id: 'd', text: 'None' },
    ]),
    correctAnswer: 'c',
    explanation: 'All three are deciduous trees that shed their leaves seasonally. Jackfruit and Mahua are deciduous, and Teak is also deciduous (unlike many tropical trees that are evergreen).',
    difficulty: 'Hard',
    questionType: 'Factual',
  },
  {
    year: 2023,
    subject: 'Science',
    topic: 'Biology',
    questionText: 'Which one of the following makes a tool with a stick to scrape insects from a hole in a tree or a log of wood?',
    options: JSON.stringify([
      { id: 'a', text: 'Chimpanzee' },
      { id: 'b', text: 'Orangutan' },
      { id: 'c', text: 'Eagle' },
      { id: 'd', text: 'Crow' },
    ]),
    correctAnswer: 'a',
    explanation: 'Chimpanzees are known to use tools, including sticks to extract termites or insects from tree holes. This behavior was documented by Jane Goodall and is a hallmark of chimpanzee intelligence.',
    difficulty: 'Easy',
    questionType: 'Factual',
  },
  {
    year: 2023,
    subject: 'Science',
    topic: 'Agriculture',
    questionText: 'Which one of the following best describes the concept of "Small Farmer Large Field"?',
    options: JSON.stringify([
      { id: 'a', text: 'A government scheme for land consolidation' },
      { id: 'b', text: 'A cooperative farming model' },
      { id: 'c', text: 'A farm mechanization program' },
      { id: 'd', text: 'An organic farming initiative' },
    ]),
    correctAnswer: 'b',
    explanation: 'Small Farmer Large Field (SFLF) is a cooperative model where small and marginal farmers pool their land and resources to achieve economies of scale. It originated in China and has been adopted in parts of India.',
    difficulty: 'Medium',
    questionType: 'Factual',
  },
  {
    year: 2023,
    subject: 'Current Affairs',
    topic: 'Defense',
    questionText: 'With reference to green hydrogen, consider the following statements: 1. It can be used directly as a fuel for internal combustion. 2. It can be blended with natural gas and used in existing pipelines. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'c',
    explanation: 'Both statements are correct. Green hydrogen (produced by electrolysis using renewable energy) can be used in modified internal combustion engines and can be blended with natural gas (up to 20%) in existing pipelines.',
    difficulty: 'Medium',
    questionType: 'StatementBased',
  },

  // ==================== 2022 UPSC PRELIMS ====================
  {
    year: 2022,
    subject: 'Polity',
    topic: 'Federalism',
    questionText: 'Consider the following statements: 1. Pursuant to the report of H.N. Sanyal Committee, the Contempt of Courts Act, 1971 was passed. 2. The Constitution of India empowers the State Legislature to legislate on the contempt of courts. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'd',
    explanation: 'Statement 1 is incorrect: Contempt of Courts Act was passed in 1971 based on the Sanyal Committee report (1961), but the Act was enacted by Parliament. Statement 2 is incorrect: Only Parliament can legislate on contempt of courts (Entry 77, Union List).',
    difficulty: 'Hard',
    questionType: 'StatementBased',
  },
  {
    year: 2022,
    subject: 'Polity',
    topic: 'Fundamental Rights',
    questionText: 'With reference to India, consider the following statements: 1. Government law officers and legal firms are recognised as advocates, but corporate lawyers and patent attorneys are not recognised as advocates. 2. The Advocates Act, 1961 provides for the State Bar Councils and the Bar Council of India. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'b',
    explanation: 'Statement 1 is incorrect: Corporate lawyers and patent attorneys ARE recognized as advocates if they are enrolled with a State Bar Council. Statement 2 is correct: The Advocates Act, 1961 establishes State Bar Councils and the Bar Council of India.',
    difficulty: 'Medium',
    questionType: 'StatementBased',
  },
  {
    year: 2022,
    subject: 'Economy',
    topic: 'International Organizations',
    questionText: '"Rapid Financing Instrument" and "Rapid Credit Facility" are related to the provisions of lending by which one of the following?',
    options: JSON.stringify([
      { id: 'a', text: 'Asian Development Bank' },
      { id: 'b', text: 'International Monetary Fund' },
      { id: 'c', text: 'World Bank' },
      { id: 'd', text: 'New Development Bank' },
    ]),
    correctAnswer: 'b',
    explanation: 'Both RFI and RFI are lending instruments of the International Monetary Fund (IMF). RFI provides rapid financial assistance with conditionality, while RCF is for low-income countries with concessional terms.',
    difficulty: 'Easy',
    questionType: 'Factual',
  },
  {
    year: 2022,
    subject: 'Economy',
    topic: 'Financial Markets',
    questionText: 'With reference to the Indian economy, consider the following statements: 1. An increase in Nominal Effective Exchange Rate (NEER) indicates the appreciation of rupee. 2. An increase in Real Effective Exchange Rate (REER) indicates the appreciation of rupee. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'c',
    explanation: 'Both statements are correct. NEER is a trade-weighted exchange rate index - increase means rupee appreciation against trading partners. REER adjusts for inflation differentials - increase means real appreciation.',
    difficulty: 'Medium',
    questionType: 'StatementBased',
  },
  {
    year: 2022,
    subject: 'Economy',
    topic: 'Banking',
    questionText: 'With reference to the expenditure made by an organisation or a company, consider the following statements: 1. Acquiring new technology is capital expenditure. 2. Expenditure on research and development is revenue expenditure. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'c',
    explanation: 'Both statements are correct. Acquiring new technology (capital asset) is capital expenditure. R&D expenditure is generally treated as revenue expenditure unless it results in a capital asset (like a patent).',
    difficulty: 'Medium',
    questionType: 'StatementBased',
  },
  {
    year: 2022,
    subject: 'Geography',
    topic: 'Climatology',
    questionText: 'Which of the following is/are the possible effects on the Earth if a major solar storm (solar flare) reaches the Earth? 1. GPS and navigation systems could fail. 2. Tsunamis could occur in the equatorial regions. 3. Power grids could be damaged. Select the correct answer using the code given below:',
    options: JSON.stringify([
      { id: 'a', text: '1 and 2 only' },
      { id: 'b', text: '2 and 3 only' },
      { id: 'c', text: '1 and 3 only' },
      { id: 'd', text: '1, 2 and 3' },
    ]),
    correctAnswer: 'c',
    explanation: 'Solar storms can disrupt GPS (ionospheric disturbances) and damage power grids (induced currents). Tsunamis are caused by undersea earthquakes, not solar storms.',
    difficulty: 'Medium',
    questionType: 'StatementBased',
  },
  {
    year: 2022,
    subject: 'Geography',
    topic: 'Indian Geography',
    questionText: 'Among the following crops, which one is the most important anthropogenic source of both methane and nitrous oxide?',
    options: JSON.stringify([
      { id: 'a', text: 'Cotton' },
      { id: 'b', text: 'Rice' },
      { id: 'c', text: 'Sugarcane' },
      { id: 'd', text: 'Wheat' },
    ]),
    correctAnswer: 'b',
    explanation: 'Rice paddies are a major source of methane (from anaerobic decomposition) and nitrous oxide (from fertilizer use in flooded fields). Rice cultivation is the largest anthropogenic source of both GHGs in agriculture.',
    difficulty: 'Easy',
    questionType: 'Factual',
  },
  {
    year: 2022,
    subject: 'Environment',
    topic: 'Biodiversity',
    questionText: 'Consider the following pairs: Wetland/Lake — Location 1. Hokera Wetland — Punjab 2. Renuka Wetland — Himachal Pradesh 3. Rudrasagar Lake — Tripura 4. Sasthamkotta Lake — Tamil Nadu How many of the above pairs are correctly matched?',
    options: JSON.stringify([
      { id: 'a', text: 'Only one' },
      { id: 'b', text: 'Only two' },
      { id: 'c', text: 'Only three' },
      { id: 'd', text: 'All four' },
    ]),
    correctAnswer: 'b',
    explanation: 'Only 2 and 3 are correct. Renuka Wetland is in HP, Rudrasagar Lake is in Tripura. Hokera Wetland is in J&K (not Punjab), and Sasthamkotta Lake is in Kerala (not Tamil Nadu).',
    difficulty: 'Hard',
    questionType: 'Matching',
  },
  {
    year: 2022,
    subject: 'Science',
    topic: 'Agriculture',
    questionText: '"System of Rice Intensification" of cultivation, in which alternate wetting and drying of rice fields is practised, results in: 1. Reduced seed requirement 2. Reduced methane emission 3. Higher yield Select the correct answer using the code given below:',
    options: JSON.stringify([
      { id: 'a', text: '1 and 2 only' },
      { id: 'b', text: '2 and 3 only' },
      { id: 'c', text: '1 and 3 only' },
      { id: 'd', text: '1, 2 and 3' },
    ]),
    correctAnswer: 'd',
    explanation: 'SRI results in all three benefits: reduced seed (80-90% less), reduced methane (due to alternate wetting/drying), and higher yield (20-50% increase). It was developed in Madagascar and adopted globally.',
    difficulty: 'Easy',
    questionType: 'StatementBased',
  },
  {
    year: 2022,
    subject: 'Science',
    topic: 'Information Technology',
    questionText: 'With reference to Web 3.0, consider the following statements: 1. Web 3.0 technology enables people to control their own data. 2. In Web 3.0 world, there can be blockchain based applications. Which of the statements given above is/are correct?',
    options: JSON.stringify([
      { id: 'a', text: '1 only' },
      { id: 'b', text: '2 only' },
      { id: 'c', text: 'Both 1 and 2' },
      { id: 'd', text: 'Neither 1 nor 2' },
    ]),
    correctAnswer: 'c',
    explanation: 'Both statements are correct. Web 3.0 is the next generation internet based on blockchain, decentralization, and token-based economics. It emphasizes user control over data and supports blockchain applications.',
    difficulty: 'Easy',
    questionType: 'StatementBased',
  },
  {
    year: 2022,
    subject: 'Current Affairs',
    topic: 'Information Technology',
    questionText: 'Consider the following: 1. Aarogya Setu 2. CoWIN 3. DigiLocker 4. DIKSHA Which of the above are built on top of open-source digital platforms?',
    options: JSON.stringify([
      { id: 'a', text: '1, 2 and 3 only' },
      { id: 'b', text: '1, 3 and 4 only' },
      { id: 'c', text: '2, 3 and 4 only' },
      { id: 'd', text: 'All of the above' },
    ]),
    correctAnswer: 'd',
    explanation: 'All four are built on open-source platforms. Aarogya Setu uses open-source framework, CoWIN is built on open-source platform, DigiLocker uses open-source, and DIKSHA is also open-source.',
    difficulty: 'Medium',
    questionType: 'Factual',
  },
];

async function main() {
  console.log('Starting database seed...');
  
  // Delete existing data
  await prisma.recommendation.deleteMany();
  await prisma.mistakeCard.deleteMany();
  await prisma.response.deleteMany();
  await prisma.testSession.deleteMany();
  await prisma.student.deleteMany();
  await prisma.pyqQuestion.deleteMany();
  
  // Insert PYQ questions
  for (const pyq of pyqData) {
    await prisma.pyqQuestion.create({
      data: pyq,
    });
  }
  
  const count = await prisma.pyqQuestion.count();
  console.log(`✅ Seed completed: ${count} questions added to database`);
  
  // Create a sample student
  const student = await prisma.student.create({
    data: {
      name: 'Test Student',
      email: 'test@upscacademy.com',
      targetExam: 'UPSC CSE 2027',
    },
  });
  console.log(`✅ Created sample student: ${student.name} (${student.email})`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
